# Generated by Django 4.0.4 on 2022-06-04 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0003_alter_teacher_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام دوره ')),
                ('programming_languege', models.CharField(max_length=100, verbose_name='زبان برنامه نویسی')),
                ('image', models.ImageField(upload_to='', verbose_name='تصویر دوره')),
                ('start_date', models.DateTimeField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateTimeField(verbose_name='تاریخ پایان')),
                ('special', models.BooleanField(verbose_name='ویژه')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.teacher', verbose_name='استاد')),
            ],
        ),
    ]
