# Generated by Django 4.0.4 on 2022-06-04 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام سرفصل')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Course.course', verbose_name='دوره ')),
            ],
        ),
    ]
