# Generated by Django 4.0.4 on 2022-06-04 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Season', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='season',
            options={'verbose_name': 'سرفصل', 'verbose_name_plural': 'سرفصل ها'},
        ),
    ]
