# Generated by Django 4.0.4 on 2022-06-04 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Lesson', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='practice')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lesson.lesson', verbose_name='نام درس')),
            ],
        ),
    ]
