# Generated by Django 4.0.4 on 2022-06-04 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Lesson', '0001_initial'),
        ('Season', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Season.season'),
        ),
    ]
