# Generated by Django 4.0.4 on 2022-06-04 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lesson', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': 'درس', 'verbose_name_plural': 'دروس'},
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='Question',
        ),
        migrations.AddField(
            model_name='lesson',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات '),
        ),
    ]
