# Generated by Django 4.0.4 on 2022-06-04 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Specialty', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialty',
            options={'verbose_name': 'تجربه', 'verbose_name_plural': 'تجربیات '},
        ),
    ]
