# Generated by Django 4.0.4 on 2022-06-03 23:57

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='نام')),
                ('password', models.CharField(blank=True, max_length=50, verbose_name='رمز عبور')),
                ('family_name', models.CharField(max_length=100, verbose_name='نام خانوادگی ')),
                ('birth_date', django_jalali.db.models.jDateField(verbose_name='تاریخ تولد')),
                ('biography', models.TextField(verbose_name='معرفی خود ')),
                ('phone_number', models.CharField(max_length=11, verbose_name='شماره تلفن')),
                ('image', models.ImageField(upload_to='', verbose_name='تصویر پروفایل')),
            ],
        ),
    ]
